global:
  scrape_interval: 15s
scrape_configs:
  - job_name: kube-state-metrics
    honor_timestamps: true
    scrape_interval: 1m
    scrape_timeout: 1m
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - '13.200.12.143:31000'
      - '65.0.71.6:31000'

  - job_name: node-exporter
    honor_timestamps: true
    scrape_interval: 1m
    scrape_timeout: 1m
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
        - '13.200.12.143:31001'
        - '65.0.71.6:31001'

  - job_name: cadvisor
    static_configs:
    - targets:
      - '13.200.12.143:31002'
      - '65.0.71.6:31002'

rule_files:
  - "/etc/prometheus/rules.yml"