---
apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: cadvisor
  labels:
    name: cadvisor
spec:
  type: NodePort 
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 31002
  selector:
    name: cadvisor
